project:
  type: website
  render:
    - index.qmd
    - data.qmd
    - participation.qmd
    - contact.qmd

website:
  title: "ElmNET"
  site-url: "https://elmnet-ulaevis.github.io/"

  navbar:
    left:
      - href: index.qmd
        text: Project
      - href: data.qmd
        text: Data
      - href: participation.qmd
        text: Participation
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual